=== testo/tjf/extended-schema-v1.0.5.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "A data object exported by Testo applications",
    "type": "object",
    "properties": {
        "schemaVersion": {
            "description": "The version of the schema that this exported data set validates against",
            "type": "string",
            "pattern": "^[1-9].[0-9].[0-9]$"
        },
        "channels": {
            "description": "The measurement channels of all connected devices",
            "type": "array",
            "minItems": 1,
            "items": { "$ref": "#/definitions/channel" }
        },
        "device": {
            "description": "The array of objects describing the connected devices, or, in case the Testo application can only connect to a single device, an object",
            "type": [ "object", "array" ],
            "minItems": 1,
            "items": { "$ref": "#/definitions/device" }
        },
        "properties": {
            "description": "Specific properties of the measurement described by the whole data set",
            "type": "array",
            "items": { "$ref": "#/definitions/measurementproperty" }
        },
        "timeStamp": {
            "description": "The time when the whole data set was created, either as a unix timestamp or as a date in ISO string format",
            "type": [ "number", "string" ]
        },
        "type": {
            "description": "An object containing information about the type of measurement that is represented by the whole data set",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the current measurement type in the language currently selected in the application",
                    "type": "string"
                },
                "id": {
                    "description": "The id of the current measurement type",
                    "type": "string",
                    "optional": true
                }
            },
            "required": [ "name" ]
        },
        "additionalMeasurementInformation": {
            "description": "Additional properties that a measurement can have",
            "type": "array",
            "items": { "$ref": "#/definitions/measurementadditionalproperty" }
        }
    },
    "anyOf": [
        { "required": [ "channels", "device", "properties", "timeStamp", "type" ] },
        { "required": [ "channels", "device", "properties", "timeStamp", "type", "additionalMeasurementInformation" ] }
    ],
    "additionalProperties": false,
    "definitions": {
        "channelunit": {
            "description": "An object describing the unit of a data channel",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The unit of the channel as a string",
                    "type": "string"
                },
                "xmlid": {
                    "description": "ZIV mapping id",
                    "type":"string",
                    "optional": true
                }
            },
            "required": [ "name" ],
            "additionalProperties": false
        },
        "channeltype": {
            "description": "An object describing the type of a data channel",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the channel as a string",
                    "type": "string"
                },
                "description": {
                    "description": "The displayed and translated name of the channel",
                    "type": "string",
                    "optional": true
                },
                "xmlid": {
                    "description": "ZIV mapping id",
                    "type":"string",
                    "optional": true
                }
            },
            "required": [ "name" ],
            "additionalProperties": false
        },
        "channel": {
            "description": "An object describing a channel",
            "type": "object",
            "properties": {
                "type": { "$ref": "#/definitions/channeltype" },
                "unit": { "$ref": "#/definitions/channelunit" },
                "values": {
                    "description": "An array containing the measurement values",
                    "type": "array",
                    "minItems": 1,
                    "items": { "$ref": "#/definitions/measurementvalue" }
                }
            },
            "required": [ "type", "unit", "values" ],
            "additionalProperties": false
        },
        "measurementvalueadditionaldata": {
            "description": "An object describing additional properties a measurement value can have, like dilution factors or flags like the NOX flag",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "description": "The value in textual form and appropriately translated",
                    "type": "string"
                },
                "value": {
                    "description": "The value that the property has",
                    "type": [ "number", "boolean" ]
                }
            },
            "anyOf": [
                { "required": [ "name", "description" ] },
                { "required": [ "name", "value" ] },
                { "required": [ "name", "value", "description" ] }
            ],
            "additionalProperties": false
        },
        "measurementvalue": {
            "description": "An object describing a measurement value",
            "type": "object",
            "properties": {
                "description": {
                    "description": "The measurement value in string form, with appropriate formatting applied",
                    "type": "string"
                },
                "value": {
                    "description": "The actual measurement value as a number",
                    "type": "number"
                },
                "exponent": {
                    "description": "The precision of the measurement value (depending on the Testo application it can be either the value of x in 10^x or the number of decimal places)",
                    "type": "integer"
                },
                "timeStamp": {
                    "description": "The time when this measurement value was created, either as a unix timestamp or as a date in ISO string format",
                    "type": [ "number", "string" ]
                },
                "additionalData": {
                    "descriptions": "An array containing additional data objects a measurement value can have",
                    "type": "array",
                    "items": { "$ref": "#/definitions/measurementvalueadditionaldata" }
                }
            },
            "anyOf": [
                { "required": [ "description", "value", "timeStamp" ] },
                { "required": [ "description", "value", "exponent", "timeStamp" ] },
                { "required": [ "description", "value", "exponent", "timeStamp", "additionalData" ] }
            ],
            "additionalProperties": false
        },
        "measurementpropertyvalue": {
            "description": "An object describing a value of a measurement property",
            "type": "object",
            "properties": {
                "description": {
                    "description": "The value in textual form including a unit",
                    "type": "string"
                },
                "name": {
                    "description": "The name of the value, usually a translated string",
                    "type": "string"
                },
                "value": {
                    "description": "The actual value",
                    "type": "number"
                },
                "id": {
                    "description": "A language agnostic id",
                    "type": "string",
                    "optional": true
                }
            },
            "required": [ "name", "value", "description" ],
            "additionalProperties": false
        },
        "measurementproperty": {
            "description": "A description of a specific property of a measurement, like fuel parameters for example",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the property",
                    "type": "string"
                },
                "description": {
                    "description": "The description of the property",
                    "type": "string"
                },
                "id": {
                    "description": "The id of the property",
                    "type": "number"
                },
                "values": {
                    "description": "An array containing objects that describe a value of a measurement property",
                    "type": "array",
                    "items": { "$ref": "#/definitions/measurementpropertyvalue" }
                }
            },
            "anyOf": [
                { "required": [ "name", "description", "values" ] },
                { "required": [ "name", "description", "values", "id" ] }
            ],
            "additionalProperties": false
        },
        "measurementadditionalproperty": {
            "description": "A description of an additional property of a measurement",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the property, translated into the current language of the application",
                    "type": "string"
                },
                "description": {
                    "description": "The description of the property, translated into the current language of the application",
                    "type": "string"
                }
            },
            "required": [ "name", "description" ],
            "additionalProperties": false
        },
        "device": {
            "description": "An object containing the properties of a connected device",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the device",
                    "type": "string"
                },
                "serial": {
                    "description": "The serial number of the device, either as a number or a string",
                    "type": [ "number", "string" ]
                },
                "deviceIdentifier": {
                    "description": "The identifier of the device",
                    "type": "string"
                },
                "lastServiceDate": {
                    "description": "The last service date of the device",
                    "type": "string"
                }
            },
            "anyOf": [
                { "required": [ "name", "serial" ] },
                { "required": [ "name", "serial", "deviceIdentifier", "lastServiceDate" ] }
            ],
            "additionalProperties": false
        }
    }
}

=== testo/tjf/TJF Examples/Schema1.0.2/smartprobes/01_basic_view.json
{
    "channels": [
        {
            "type": {
                "name": "501"
            },
            "unit": {
                "name": "bar"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "rel",
                            "name": "valueType"
                        }
                    ],
                    "description": "1,43",
                    "exponent": 2,
                    "timeStamp": "2017-07-26T14:08:49",
                    "value": 1.4330124855041504
                }
            ]
        },
        {
            "type": {
                "name": "600"
            },
            "unit": {
                "name": "°C"
            },
            "values": [
                {
                    "description": "19,6",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T14:08:49",
                    "value": 19.562957763671875
                }
            ]
        },
        {
            "type": {
                "name": "600"
            },
            "unit": {
                "name": "%RH"
            },
            "values": [
                {
                    "description": "98,9",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T14:08:49",
                    "value": 98.90737915039062
                }
            ]
        },
        {
            "type": {
                "name": "600"
            },
            "unit": {
                "name": "°C td"
            },
            "values": [
                {
                    "description": "19,4",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T14:08:49",
                    "value": 19.422027587890625
                }
            ]
        },
        {
            "type": {
                "name": "600"
            },
            "unit": {
                "name": "wb °C"
            },
            "values": [
                {
                    "description": "19,5",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T14:08:49",
                    "value": 19.477264404296875
                }
            ]
        },
        {
            "type": {
                "name": "502"
            },
            "unit": {
                "name": "bar"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "rel",
                            "name": "valueType"
                        }
                    ],
                    "description": "1,25",
                    "exponent": 2,
                    "timeStamp": "2017-07-26T14:08:49",
                    "value": 1.25
                }
            ]
        },
        {
            "type": {
                "name": "601"
            },
            "unit": {
                "name": "°C"
            },
            "values": [
                {
                    "description": "-11,7",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T14:08:49",
                    "value": -11.755706787109375
                }
            ]
        },
        {
            "type": {
                "name": "601"
            },
            "unit": {
                "name": "%RH"
            },
            "values": [
                {
                    "description": "20,6",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T14:08:49",
                    "value": 20.610736846923828
                }
            ]
        },
        {
            "type": {
                "name": "601"
            },
            "unit": {
                "name": "°C td"
            },
            "values": [
                {
                    "description": "-28,1",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T14:08:49",
                    "value": -28.157867431640625
                }
            ]
        },
        {
            "type": {
                "name": "601"
            },
            "unit": {
                "name": "wb °C"
            },
            "values": [
                {
                    "description": "-14,0",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T14:08:49",
                    "value": -14.036407470703125
                }
            ]
        }
    ],
    "device": [
        {
            "name": "testo 605i",
            "serial": "14029600"
        },
        {
            "name": "testo 549i",
            "serial": "13379501"
        },
        {
            "name": "testo 549i",
            "serial": "13379502"
        },
        {
            "name": "testo 605i",
            "serial": "14029601"
        }
    ],
    "properties": [
    ],
    "schemaVersion": "1.0.2",
    "timeStamp": "2017-07-26T14:08:49",
    "type": {
        "name": "Standardansicht"
    }
}
