=== testo/tjf/extended-schema-v1.0.5.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "A data object exported by Testo applications",
    "type": "object",
    "properties": {
        "schemaVersion": {
            "description": "The version of the schema that this exported data set validates against",
            "type": "string",
            "pattern": "^[1-9].[0-9].[0-9]$"
        },
        "channels": {
            "description": "The measurement channels of all connected devices",
            "type": "array",
            "minItems": 1,
            "items": { "$ref": "#/definitions/channel" }
        },
        "device": {
            "description": "The array of objects describing the connected devices, or, in case the Testo application can only connect to a single device, an object",
            "type": [ "object", "array" ],
            "minItems": 1,
            "items": { "$ref": "#/definitions/device" }
        },
        "properties": {
            "description": "Specific properties of the measurement described by the whole data set",
            "type": "array",
            "items": { "$ref": "#/definitions/measurementproperty" }
        },
        "timeStamp": {
            "description": "The time when the whole data set was created, either as a unix timestamp or as a date in ISO string format",
            "type": [ "number", "string" ]
        },
        "type": {
            "description": "An object containing information about the type of measurement that is represented by the whole data set",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the current measurement type in the language currently selected in the application",
                    "type": "string"
                },
                "id": {
                    "description": "The id of the current measurement type",
                    "type": "string",
                    "optional": true
                }
            },
            "required": [ "name" ]
        },
        "additionalMeasurementInformation": {
            "description": "Additional properties that a measurement can have",
            "type": "array",
            "items": { "$ref": "#/definitions/measurementadditionalproperty" }
        }
    },
    "anyOf": [
        { "required": [ "channels", "device", "properties", "timeStamp", "type" ] },
        { "required": [ "channels", "device", "properties", "timeStamp", "type", "additionalMeasurementInformation" ] }
    ],
    "additionalProperties": false,
    "definitions": {
        "channelunit": {
            "description": "An object describing the unit of a data channel",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The unit of the channel as a string",
                    "type": "string"
                },
                "xmlid": {
                    "description": "ZIV mapping id",
                    "type":"string",
                    "optional": true
                }
            },
            "required": [ "name" ],
            "additionalProperties": false
        },
        "channeltype": {
            "description": "An object describing the type of a data channel",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the channel as a string",
                    "type": "string"
                },
                "description": {
                    "description": "The displayed and translated name of the channel",
                    "type": "string",
                    "optional": true
                },
                "xmlid": {
                    "description": "ZIV mapping id",
                    "type":"string",
                    "optional": true
                }
            },
            "required": [ "name" ],
            "additionalProperties": false
        },
        "channel": {
            "description": "An object describing a channel",
            "type": "object",
            "properties": {
                "type": { "$ref": "#/definitions/channeltype" },
                "unit": { "$ref": "#/definitions/channelunit" },
                "values": {
                    "description": "An array containing the measurement values",
                    "type": "array",
                    "minItems": 1,
                    "items": { "$ref": "#/definitions/measurementvalue" }
                }
            },
            "required": [ "type", "unit", "values" ],
            "additionalProperties": false
        },
        "measurementvalueadditionaldata": {
            "description": "An object describing additional properties a measurement value can have, like dilution factors or flags like the NOX flag",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "description": "The value in textual form and appropriately translated",
                    "type": "string"
                },
                "value": {
                    "description": "The value that the property has",
                    "type": [ "number", "boolean" ]
                }
            },
            "anyOf": [
                { "required": [ "name", "description" ] },
                { "required": [ "name", "value" ] },
                { "required": [ "name", "value", "description" ] }
            ],
            "additionalProperties": false
        },
        "measurementvalue": {
            "description": "An object describing a measurement value",
            "type": "object",
            "properties": {
                "description": {
                    "description": "The measurement value in string form, with appropriate formatting applied",
                    "type": "string"
                },
                "value": {
                    "description": "The actual measurement value as a number",
                    "type": "number"
                },
                "exponent": {
                    "description": "The precision of the measurement value (depending on the Testo application it can be either the value of x in 10^x or the number of decimal places)",
                    "type": "integer"
                },
                "timeStamp": {
                    "description": "The time when this measurement value was created, either as a unix timestamp or as a date in ISO string format",
                    "type": [ "number", "string" ]
                },
                "additionalData": {
                    "descriptions": "An array containing additional data objects a measurement value can have",
                    "type": "array",
                    "items": { "$ref": "#/definitions/measurementvalueadditionaldata" }
                }
            },
            "anyOf": [
                { "required": [ "description", "value", "timeStamp" ] },
                { "required": [ "description", "value", "exponent", "timeStamp" ] },
                { "required": [ "description", "value", "exponent", "timeStamp", "additionalData" ] }
            ],
            "additionalProperties": false
        },
        "measurementpropertyvalue": {
            "description": "An object describing a value of a measurement property",
            "type": "object",
            "properties": {
                "description": {
                    "description": "The value in textual form including a unit",
                    "type": "string"
                },
                "name": {
                    "description": "The name of the value, usually a translated string",
                    "type": "string"
                },
                "value": {
                    "description": "The actual value",
                    "type": "number"
                },
                "id": {
                    "description": "A language agnostic id",
                    "type": "string",
                    "optional": true
                }
            },
            "required": [ "name", "value", "description" ],
            "additionalProperties": false
        },
        "measurementproperty": {
            "description": "A description of a specific property of a measurement, like fuel parameters for example",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the property",
                    "type": "string"
                },
                "description": {
                    "description": "The description of the property",
                    "type": "string"
                },
                "id": {
                    "description": "The id of the property",
                    "type": "number"
                },
                "values": {
                    "description": "An array containing objects that describe a value of a measurement property",
                    "type": "array",
                    "items": { "$ref": "#/definitions/measurementpropertyvalue" }
                }
            },
            "anyOf": [
                { "required": [ "name", "description", "values" ] },
                { "required": [ "name", "description", "values", "id" ] }
            ],
            "additionalProperties": false
        },
        "measurementadditionalproperty": {
            "description": "A description of an additional property of a measurement",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the property, translated into the current language of the application",
                    "type": "string"
                },
                "description": {
                    "description": "The description of the property, translated into the current language of the application",
                    "type": "string"
                }
            },
            "required": [ "name", "description" ],
            "additionalProperties": false
        },
        "device": {
            "description": "An object containing the properties of a connected device",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the device",
                    "type": "string"
                },
                "serial": {
                    "description": "The serial number of the device, either as a number or a string",
                    "type": [ "number", "string" ]
                },
                "deviceIdentifier": {
                    "description": "The identifier of the device",
                    "type": "string"
                },
                "lastServiceDate": {
                    "description": "The last service date of the device",
                    "type": "string"
                }
            },
            "anyOf": [
                { "required": [ "name", "serial" ] },
                { "required": [ "name", "serial", "deviceIdentifier", "lastServiceDate" ] }
            ],
            "additionalProperties": false
        }
    }
}

=== testo/tjf/TJF Examples/Schema1.0.2/smartprobes/08_tightness_test.json
{
    "channels": [
        {
            "type": {
                "name": ""
            },
            "unit": {
                "name": "mbar"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "P Start",
                            "name": "valueType"
                        }
                    ],
                    "description": "11,74",
                    "exponent": 2,
                    "timeStamp": "2017-07-26T13:40:02",
                    "value": 11.737770080566406
                }
            ]
        },
        {
            "type": {
                "name": "500"
            },
            "unit": {
                "name": "mbar"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "P aktuell",
                            "name": "valueType"
                        }
                    ],
                    "description": "11,93",
                    "exponent": 2,
                    "timeStamp": "2017-07-26T13:40:02",
                    "value": 11.934261322021484
                }
            ]
        },
        {
            "type": {
                "name": ""
            },
            "unit": {
                "name": "mbar"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "ΔP aktuell",
                            "name": "valueType"
                        }
                    ],
                    "description": "0,19",
                    "exponent": 2,
                    "timeStamp": "2017-07-26T13:40:02",
                    "value": 0.1900005340576172
                }
            ]
        },
        {
            "type": {
                "name": "3"
            },
            "unit": {
                "name": "mbar"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "P Alarm",
                            "name": "valueType"
                        }
                    ],
                    "description": "-8,26",
                    "exponent": 2,
                    "timeStamp": "2017-07-26T13:40:02",
                    "value": -8.262228012084961
                }
            ]
        }
    ],
    "device": [
        {
            "name": "testo 510i",
            "serial": "13379500"
        }
    ],
    "properties": [
        {
            "description": "timings",
            "name": "timings",
            "values": [
                {
                    "description": "0 min",
                    "name": "stabilisationTime",
                    "value": 0
                },
                {
                    "description": "1 min",
                    "name": "testTime",
                    "value": 1
                }
            ]
        }
    ],
    "schemaVersion": "1.0.2",
    "timeStamp": "2017-07-26T13:40:02",
    "type": {
        "name": "Dichtigkeitstest"
    }
}

=== testo/tjf/TJF Examples/Schema1.0.2/smartprobes/06_temperature_ir.json
{
    "channels": [
        {
            "type": {
                "name": "179"
            },
            "unit": {
                "name": "°C"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "IR",
                            "name": "valueType"
                        }
                    ],
                    "description": "26,6",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T11:00:08",
                    "value": 26.574432373046875
                }
            ]
        }
    ],
    "device": [
        {
            "name": "testo 805i",
            "serial": "49614179"
        }
    ],
    "properties": [
        {
            "description": "materialEmission",
            "name": "materialEmission",
            "values": [
                {
                    "description": "0,66",
                    "name": "materialEmissionValue",
                    "value": 0.6600000262260437
                }
            ]
        }
    ],
    "schemaVersion": "1.0.2",
    "timeStamp": "2017-07-26T11:00:08",
    "type": {
        "name": "Temperatur (IR)"
    }
}

=== testo/tjf/TJF Examples/Schema1.0.2/smartprobes/09_cooling_heating_power.json
{
    "channels": [
        {
            "type": {
                "name": "601"
            },
            "unit": {
                "name": "%RH"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "Abluft",
                            "name": "airtype"
                        }
                    ],
                    "description": "0,0",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T13:44:29",
                    "value": 0
                }
            ]
        },
        {
            "type": {
                "name": "600"
            },
            "unit": {
                "name": "%RH"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "Zuluft",
                            "name": "airtype"
                        }
                    ],
                    "description": "16,5",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T13:44:29",
                    "value": 16.543468475341797
                }
            ]
        },
        {
            "type": {
                "name": "601"
            },
            "unit": {
                "name": "°C"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "Abluft",
                            "name": "airtype"
                        }
                    ],
                    "description": "-20,0",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T13:44:29",
                    "value": -20
                }
            ]
        },
        {
            "type": {
                "name": "600"
            },
            "unit": {
                "name": "°C"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "Zuluft",
                            "name": "airtype"
                        }
                    ],
                    "description": "-13,3",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T13:44:29",
                    "value": -13.382598876953125
                }
            ]
        },
        {
            "type": {
                "name": ""
            },
            "unit": {
                "name": "cfm"
            },
            "values": [
                {
                    "description": "1.500",
                    "exponent": 0,
                    "timeStamp": "2017-07-26T13:44:29",
                    "value": 1499.999755859375
                }
            ]
        },
        {
            "type": {
                "name": ""
            },
            "unit": {
                "name": "BTU/h"
            },
            "values": [
                {
                    "description": "24.218",
                    "exponent": 0,
                    "timeStamp": "2017-07-26T13:44:29",
                    "value": 24218.0078125
                }
            ]
        }
    ],
    "device": [
        {
            "name": "testo 605i",
            "serial": "14029601"
        },
        {
            "name": "testo 605i",
            "serial": "14029600"
        }
    ],
    "properties": [
    ],
    "schemaVersion": "1.0.2",
    "timeStamp": "2017-07-26T13:44:29",
    "type": {
        "name": "Kühl- / Heizleistung"
    }
}

=== testo/tjf/TJF Examples/Schema1.0.2/smartprobes/02_volume_flow_outlet.json
{
    "channels": [
        {
            "type": {
                "name": "400"
            },
            "unit": {
                "name": "°C"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "Abluft",
                            "name": "airtype"
                        },
                        {
                            "description": "Einzel",
                            "name": "measurementmode"
                        }
                    ],
                    "description": "28,5",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T10:31:07",
                    "value": 28.454925537109375
                },
                {
                    "additionalData": [
                        {
                            "description": "Abluft",
                            "name": "airtype"
                        },
                        {
                            "description": "Einzel",
                            "name": "measurementmode"
                        }
                    ],
                    "description": "27,5",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T10:31:08",
                    "value": 27.499969482421875
                },
                {
                    "additionalData": [
                        {
                            "description": "Abluft",
                            "name": "airtype"
                        },
                        {
                            "description": "Einzel",
                            "name": "measurementmode"
                        }
                    ],
                    "description": "25,7",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T10:31:14",
                    "value": 25.669830322265625
                }
            ]
        },
        {
            "type": {
                "name": "400"
            },
            "unit": {
                "name": "m/s"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "Abluft",
                            "name": "airtype"
                        },
                        {
                            "description": "Einzel",
                            "name": "measurementmode"
                        }
                    ],
                    "description": "18,46",
                    "exponent": 2,
                    "timeStamp": "2017-07-26T10:31:07",
                    "value": 18.454914093017578
                },
                {
                    "additionalData": [
                        {
                            "description": "Abluft",
                            "name": "airtype"
                        },
                        {
                            "description": "Einzel",
                            "name": "measurementmode"
                        }
                    ],
                    "description": "17,50",
                    "exponent": 2,
                    "timeStamp": "2017-07-26T10:31:08",
                    "value": 17.5
                },
                {
                    "additionalData": [
                        {
                            "description": "Abluft",
                            "name": "airtype"
                        },
                        {
                            "description": "Einzel",
                            "name": "measurementmode"
                        }
                    ],
                    "description": "15,67",
                    "exponent": 2,
                    "timeStamp": "2017-07-26T10:31:14",
                    "value": 15.669872283935547
                }
            ]
        },
        {
            "type": {
                "name": "400"
            },
            "unit": {
                "name": "m³/h"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "Abluft",
                            "name": "airtype"
                        },
                        {
                            "description": "Einzel",
                            "name": "measurementmode"
                        }
                    ],
                    "description": "7.975",
                    "exponent": 0,
                    "timeStamp": "2017-07-26T10:31:07",
                    "value": 7974.7177734375
                },
                {
                    "additionalData": [
                        {
                            "description": "Abluft",
                            "name": "airtype"
                        },
                        {
                            "description": "Einzel",
                            "name": "measurementmode"
                        }
                    ],
                    "description": "7.560",
                    "exponent": 0,
                    "timeStamp": "2017-07-26T10:31:08",
                    "value": 7559.998046875
                },
                {
                    "additionalData": [
                        {
                            "description": "Abluft",
                            "name": "airtype"
                        },
                        {
                            "description": "Einzel",
                            "name": "measurementmode"
                        }
                    ],
                    "description": "6.769",
                    "exponent": 0,
                    "timeStamp": "2017-07-26T10:31:14",
                    "value": 6769.4375
                }
            ]
        }
    ],
    "device": [
        {
            "name": "testo 405i",
            "serial": "64428400"
        }
    ],
    "properties": [
    ],
    "schemaVersion": "1.0.2",
    "timeStamp": "2017-07-26T10:32:08",
    "type": {
        "name": "Volumenstrom (Auslass)"
    }
}

=== testo/tjf/TJF Examples/Schema1.0.2/smartprobes/11_triple_current.json
{
  "timeStamp" : "2017-07-26T10:08:57",
  "properties" : [

  ],
  "channels" : [
    {
      "type" : {
        "name" : "313"
      },
      "values" : [
        {
          "exponent" : 1,
          "timeStamp" : "2017-07-26T10:08:53",
          "value" : 0.1992635130882263,
          "description" : "0,2",
          "additionalData" : [
            {
              "name" : "phase",
              "description" : "Phase 1"
            }
          ]
        },
        {
          "exponent" : 1,
          "timeStamp" : "2017-07-26T10:08:53",
          "value" : 0.1992635130882263,
          "description" : "0,2",
          "additionalData" : [
            {
              "name" : "phase",
              "description" : "Phase 2"
            }
          ]
        },
        {
          "exponent" : 1,
          "timeStamp" : "2017-07-26T10:08:56",
          "value" : 0.1992635130882263,
          "description" : "0,2",
          "additionalData" : [
            {
              "name" : "phase",
              "description" : "Phase 3"
            }
          ]
        }
      ],
      "unit" : {
        "name" : "A"
      }
    }
  ],
  "device" : [
    {
      "name" : "testo 770-3",
      "serial" : "142710409313"
    }
  ],
  "schemaVersion" : "1.0.2",
  "type" : {
    "name" : "Triple Current"
  }
}

=== testo/tjf/TJF Examples/Schema1.0.2/smartprobes/10_quadruple_temperature.json
{
  "timeStamp" : "2017-07-26T10:13:32",
  "properties" : [

  ],
  "channels" : [
    {
      "type" : {
        "name" : "875"
      },
      "values" : [
        {
          "exponent" : 1,
          "timeStamp" : "2017-07-26T10:12:52",
          "value" : 29.83517456054688,
          "description" : "29,8",
          "additionalData" : [
            {
              "name" : "unittype",
              "description" : "in (indoor unit)"
            }
          ]
        },
        {
          "exponent" : 1,
          "timeStamp" : "2017-07-26T10:13:10",
          "value" : 28.41458129882812,
          "description" : "28,4",
          "additionalData" : [
            {
              "name" : "unittype",
              "description" : "out (indoor unit)"
            }
          ]
        },
        {
          "exponent" : 1,
          "timeStamp" : "2017-07-26T10:13:16",
          "value" : 32.52127075195312,
          "description" : "32,5",
          "additionalData" : [
            {
              "name" : "unittype",
              "description" : "in (outdoor unit)"
            }
          ]
        },
        {
          "exponent" : 1,
          "timeStamp" : "2017-07-26T10:13:31",
          "value" : 34.06491088867188,
          "description" : "34,1",
          "additionalData" : [
            {
              "name" : "unittype",
              "description" : "out (outdoor unit)"
            }
          ]
        }
      ],
      "unit" : {
        "name" : "Â°C"
      }
    }
  ],
  "device" : [
    {
      "name" : "testo 905i",
      "serial" : "49505875"
    }
  ],
  "schemaVersion" : "1.0.2",
  "type" : {
    "name" : "Quadruple Temperature"
  }
}
