=== testo/tjf/schema/slim-schema-v1.1.0.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "A data object exported by Testo applications",
    "type": "object",
    "properties": {
        "schemaVersion": {
            "description": "The version of the schema that this exported data set validates against",
            "type": "string",
            "pattern": "^[1-9].[0-9].[0-9]$"
        },
        "channels": {
            "description": "The measurement channels of all connected devices",
            "type": "array",
            "minItems": 1,
            "items": { "$ref": "#/definitions/channel" }
        },
        "device": {
            "description": "The array of objects describing the connected devices, or, in case the Testo application can only connect to a single device, an object",
            "type": [ "object", "array" ],
            "minItems": 1,
            "items": { "$ref": "#/definitions/device" }
        },
        "customer": {
          "description": "Customer contact information",
          "type": "object",
          "$ref": "#/definitions/contact"
        },
        "organisation": {
          "description": "Organisation contact information",
          "type": "object" ,
          "$ref": "#/definitions/contact"
        },
        "measuringPoint": {
          "description": "Measuring point of current measurement",
          "type": "object",
          "$ref": "#/definitions/measuringpoint"
        },
        "properties": {
            "description": "Specific properties of the measurement described by the whole data set",
            "type": "array",
            "items": { "$ref": "#/definitions/measurementproperty" }
        },
        "results": {
            "description": "results of the measurement",
            "type": "array",
            "items": { "$ref": "#/definitions/measurementproperty" }
        },
        "timeStamp": {
            "description": "The time when the whole data set was created, either as a unix timestamp or as a date in ISO string format",
            "type": [ "number", "string" ]
        },
        "type": {
            "description": "An object containing information about the type of measurement that is represented by the whole data set",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the current measurement type in the language currently selected in the application",
                    "type": "string"
                },
                "id": {
                    "description": "The id of the current measurement type",
                    "type": "string",
                    "optional": true
                }
            },
            "required": [ "name" ]
        },
        "additionalMeasurementInformation": {
            "description": "Additional properties that a measurement can have",
            "type": "array",
            "items": { "$ref": "#/definitions/measurementadditionalproperty" }
        },
        "images": {
            "description": "name of images (not included in json but for example included in email when exported with T400)",
            "type": "array",
            "items": { "type": "string" },
            "optional": true
        }
    },
    "anyOf": [
        { "required": [ "channels", "device", "timeStamp", "type" ] },
        { "required": [ "channels", "device", "properties", "timeStamp", "type" ] },
        { "required": [ "channels", "device", "properties", "timeStamp", "type", "additionalMeasurementInformation" ] }
    ],
    "additionalProperties": false,
    "definitions": {
        "channelunit": {
            "description": "An object describing the unit of a data channel",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The unit of the channel as a string",
                    "type": "string"
                },
                "xmlid": {
                    "description": "ZIV mapping id",
                    "type":"string",
                    "optional": true
                }
            },
            "required": [ "name" ],
            "additionalProperties": false
        },
        "channeltype": {
            "description": "An object describing the type of a data channel",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the channel as a string",
                    "type": "string"
                },
                "description": {
                    "description": "The displayed and translated name of the channel",
                    "type": "string",
                    "optional": true
                },
                "xmlid": {
                    "description": "ZIV mapping id",
                    "type":"string",
                    "optional": true
                }
            },
            "required": [ "name" ],
            "additionalProperties": false
        },
        "channel": {
            "description": "An object describing a channel",
            "type": "object",
            "properties": {
                "type": { "$ref": "#/definitions/channeltype" },
                "unit": { "$ref": "#/definitions/channelunit" },
                "additionalData": {
                  "items": { "$ref": "#/definitions/additionalData" }
                },
                "alarmData": {
                    "items": { "$ref": "#/definitions/alarmData" }
                },
                "values": {
                    "description": "An array containing the measurement values",
                    "type": "array",
                    "minItems": 1,
                    "items": { "$ref": "#/definitions/measurementvalue" }
                }
            },
            "required": [ "type", "unit", "values" ],
            "additionalProperties": false
        },
        "measurementvalueadditionaldata": {
            "description": "An object describing additional properties a measurement value can have, like dilution factors or flags like the NOX flag",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "description": "The value in textual form and appropriately translated",
                    "type": "string"
                },
                "value": {
                    "description": "The value that the property has",
                    "type": [ "number", "boolean" ]
                }
            },
            "anyOf": [
                { "required": [ "name", "description" ] },
                { "required": [ "name", "value" ] },
                { "required": [ "name", "value", "description" ] }
            ],
            "additionalProperties": false
        },
        "measurementvalue": {
            "description": "An object describing a measurement value",
            "type": "object",
            "properties": {
                "description": {
                    "description": "The measurement value in string form, with appropriate formatting applied",
                    "type": "string"
                },
                "value": {
                    "description": "The actual measurement value in displayed unit as a number",
                    "type": "number"
                },
                "exponent": {
                    "description": "The precision of the measurement value (depending on the Testo application it can be either the value of x in 10^x or the number of decimal places)",
                    "type": "integer"
                },
                "timeStamp": {
                    "description": "The time when this measurement value was created, either as a unix timestamp or as a date in ISO string format",
                    "type": [ "number", "string" ]
                },
                "status": {
                    "description": "Status of measuement value: (e.g. invalid, overrange, underrange, empty)",
                    "type": "string"
                },
                "additionalData": {
                    "descriptions": "An array containing additional data objects a measurement value can have",
                    "type": "array",
                    "items": { "$ref": "#/definitions/measurementvalueadditionaldata" }
                }
            },
            "anyOf": [
                { "required": [ "timestamp" ] },
                { "required": [ "value", "timeStamp" ] },
                { "required": [ "description", "value", "timeStamp" ] },
                { "required": [ "description", "value", "exponent", "timeStamp" ] },
                { "required": [ "description", "value", "exponent", "timeStamp", "additionalData" ] }
            ],
            "additionalProperties": false
        },
        "measurementpropertyvalue": {
            "description": "An object describing a value of a measurement property",
            "type": "object",
            "properties": {
                "description": {
                    "description": "The value in textual form including a unit",
                    "type": "string"
                },
                "name": {
                    "description": "The name of the value, usually a translated string",
                    "type": "string"
                },
                "value": {
                    "description": "The actual value",
                    "type": [ "number", "string", "boolean" ]
                },
                "id": {
                    "description": "A language agnostic id",
                    "type": "string",
                    "optional": true
                },
                "unit": {
                    "description": "Unit of value",
                    "type": "string",
                    "optional": true
                },
                "baseUnit": {
                    "description": "The iso unit of the value",
                    "type": "string",
                    "optional": true
                },
                "precision": {
                    "description": "precision of value in value property",
                    "type": "integer",
                    "optional": true
                }
            },
            "required": [ "value" ],
            "additionalProperties": false
        },
        "measurementproperty": {
            "description": "A description of a specific property of a measurement, like fuel parameters for example",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the property",
                    "type": "string"
                },
                "description": {
                    "description": "The description of the property",
                    "type": "string"
                },
                "id": {
                    "description": "The id of the property",
                    "type": "number"
                },
                "values": {
                    "description": "An array containing objects that describe a value of a measurement property",
                    "type": "array",
                    "items": { "$ref": "#/definitions/measurementpropertyvalue" }
                }
            },
            "anyOf": [
                { "required": [ "name", "values" ] },
                { "required": [ "name", "description", "values" ] },
                { "required": [ "name", "description", "values", "id" ] }
            ],
            "additionalProperties": false
        },
        "measurementadditionalproperty": {
            "description": "A description of an additional property of a measurement",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the property, translated into the current language of the application",
                    "type": "string"
                },
                "description": {
                    "description": "The description of the property, translated into the current language of the application",
                    "type": "string"
                },
                "value": {
                    "description": "Additional value",
                    "type": [ "string", "integer", "number", "array", "object", "boolean" ],
                    "optional": true
                }
            },
            "required": [ "name" ],
            "additionalProperties": false
        },
        "device": {
            "description": "An object containing the properties of a connected device",
            "type": "object",
            "properties": {
                "name": {
                    "description": "The name of the device",
                    "type": "string"
                },
                "serial": {
                    "description": "The serial number of the device, either as a number or a string",
                    "type": [ "number", "string" ]
                },
                "deviceIdentifier": {
                    "description": "The identifier of the device",
                    "type": "string"
                },
                "partNumber": {
                    "description": "Part number of device",
                    "type": "string"
                },
                "firmwareVersion": {
                    "description": "Firmware version of device",
                    "type": "string"
                },
                "boardIndex": {
                    "type": "integer"
                },
                "lastServiceDate": {
                    "description": "The last service date of the device",
                    "type": "string"
                },
                "measCycle": {
                    "description": "Meas cycle of device in milliseconds",
                    "type": "integer"
                },
                "measTypes": {
                    "description": "Measurement types of device's channels",
                    "type": "array",
                    "items": { "type": "string" }
                },
                "additionalData": {
                  "items": { "$ref": "#/definitions/additionalData" }
                }
            },
            "anyOf": [
                { "required": [ "name", "serial" ] },
                { "required": [ "name", "serial", "deviceIdentifier", "lastServiceDate" ] }
            ],
            "additionalProperties": false
        },
        "contact": {
            "description": "An object containing contact information",
            "type": "object",
            "properties": {
              "name": {
                  "type": "string"
              },
              "street": {
                  "type": "string"
              },
              "city": {
                  "type": "string"
              },
              "country": {
                  "type": "string"
              },
              "phone": {
                  "type": "string"
              },
              "email": {
                  "type": "string"
              },
              "personOfContact": {
                  "type": "string"
              },
              "fax": {
                  "type": "string"
              },
              "homepage": {
                  "type": "string"
              },
              "logo": {
                  "type": "string"
              }
            },
            "required": [ "name" ],
            "additionalProperties": false
        },
        "measuringpoint": {
            "description": "An object containing measuring point information",
            "type": "object",
            "properties": {
              "name": {
                  "type": "string"
              },
              "systemNumber": {
                  "type": "string"
              },
              "systemType": {
                  "type": "string"
              },
              "systemManufacturer": {
                  "type": "string"
              },
              "systemSerial": {
                  "type": "string"
              },
              "yearOfConstruction": {
                  "type": "string"
              },
              "notes": {
                  "type": "string"
              },
              "additionalData": {
                "items": { "$ref": "#/definitions/measurementproperty" }
              }
            },
            "required": [ "name" ],
            "additionalProperties": false
        },
        "additionalData": {
            "description": "additional data (e.g. calibration data for devices)",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": [ "string", "number", "integer", "boolean", "object", "array" ]
                },
                "unit": {
                    "type": "string"
                }
            },
            "required": [ "name" ],
            "additionalProperties": false
        },
        "alarmData": {
            "description": "alarm data (upper, upper warning, lower limits)",
            "type": "object",
            "properties": {
                "upperAlarm": {
                    "type": "object"
                },
                "upperWarning": {
                    "type": "object"
                },
                "lowerAlarm": {
                    "type": "object"
                }
            },
            "additionalProperties": false
        }
    }
}

=== testo/tjf/TJF Examples/Schema1.0.2/smartprobes/07_mould_indication.json
{
    "channels": [
        {
            "type": {
                "name": "179"
            },
            "unit": {
                "name": "°C"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "Wand",
                            "name": "valueType"
                        }
                    ],
                    "description": "25,5",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T13:27:55",
                    "value": 25.484161376953125
                }
            ]
        },
        {
            "type": {
                "name": ""
            },
            "unit": {
                "name": "%RH"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "Wand",
                            "name": "valueType"
                        }
                    ],
                    "description": "71",
                    "exponent": 0,
                    "timeStamp": "2017-07-26T13:27:55",
                    "value": 71.0948486328125
                }
            ]
        },
        {
            "type": {
                "name": "600"
            },
            "unit": {
                "name": "°C"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "Raum",
                            "name": "valueType"
                        }
                    ],
                    "description": "19,9",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T13:27:55",
                    "value": 19.890411376953125
                }
            ]
        },
        {
            "type": {
                "name": "600"
            },
            "unit": {
                "name": "%RH"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "Raum",
                            "name": "valueType"
                        }
                    ],
                    "description": "99,7",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T13:27:55",
                    "value": 99.72608947753906
                }
            ]
        }
    ],
    "device": [
        {
            "name": "testo 805i",
            "serial": "49614179"
        },
        {
            "name": "testo 605i",
            "serial": "14029600"
        }
    ],
    "properties": [
        {
            "description": "materialEmission",
            "name": "materialEmission",
            "values": [
                {
                    "description": "0,66",
                    "name": "materialEmissionValue",
                    "value": 0.6600000262260437
                }
            ]
        },
        {
            "description": "mouldRisk",
            "name": "mouldRisk",
            "values": [
                {
                    "description": "< 65%",
                    "name": "surfaceMoistureLevel",
                    "value": "low"
                }
            ]
        }
    ],
    "schemaVersion": "1.0.2",
    "timeStamp": "2017-07-26T13:27:55",
    "type": {
        "name": "Schimmelindikation"
    }
}

=== testo/tjf/TJF Examples/Schema1.0.2/smartprobes/05_target_superheat_2.json
{
    "channels": [
        {
            "type": {
                "name": "502"
            },
            "unit": {
                "name": "bar"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "ND",
                            "name": "valueType"
                        }
                    ],
                    "description": "0,95",
                    "exponent": 2,
                    "timeStamp": "2017-07-26T10:51:16",
                    "value": 0.9477355480194092
                }
            ]
        },
        {
            "type": {
                "name": "501"
            },
            "unit": {
                "name": "bar"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "HD",
                            "name": "valueType"
                        }
                    ],
                    "description": "1,43",
                    "exponent": 2,
                    "timeStamp": "2017-07-26T10:51:16",
                    "value": 1.4330124855041504
                }
            ]
        },
        {
            "type": {
                "name": ""
            },
            "unit": {
                "name": "°C"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "to",
                            "name": "valueType"
                        }
                    ],
                    "description": "-69,7",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T10:51:16",
                    "value": -69.73434448242188
                }
            ]
        },
        {
            "type": {
                "name": ""
            },
            "unit": {
                "name": "°C"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "tc",
                            "name": "valueType"
                        }
                    ],
                    "description": "-65,2",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T10:51:16",
                    "value": -65.22189331054688
                }
            ]
        },
        {
            "type": {
                "name": "100"
            },
            "unit": {
                "name": "°C"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "toh",
                            "name": "valueType"
                        }
                    ],
                    "description": "-23,0",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T10:51:16",
                    "value": -23.090179443359375
                }
            ]
        },
        {
            "type": {
                "name": "101"
            },
            "unit": {
                "name": "°C"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "tcu",
                            "name": "valueType"
                        }
                    ],
                    "description": "-13,3",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T10:51:16",
                    "value": -13.308685302734375
                }
            ]
        },
        {
            "type": {
                "name": ""
            },
            "unit": {
                "name": "K"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "Δtoh",
                            "name": "valueType"
                        }
                    ],
                    "description": "46,7",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T10:51:16",
                    "value": 46.70001220703125
                }
            ]
        },
        {
            "type": {
                "name": ""
            },
            "unit": {
                "name": "K"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "Δtcu",
                            "name": "valueType"
                        }
                    ],
                    "description": "---",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T10:51:16",
                    "value": 9.80908925027372e-45
                }
            ]
        },
        {
            "type": {
                "name": ""
            },
            "unit": {
                "name": "K"
            },
            "values": [
                {
                    "additionalData": [
                        {
                            "description": "Zielüberhitzung",
                            "name": "valueType"
                        }
                    ],
                    "description": "4,9",
                    "exponent": 1,
                    "timeStamp": "2017-07-26T10:51:16",
                    "value": 4.888888359069824
                }
            ]
        }
    ],
    "device": [
        {
            "name": "testo 115i",
            "serial": "13379100"
        },
        {
            "name": "testo 115i",
            "serial": "13379101"
        },
        {
            "name": "testo 549i",
            "serial": "13379502"
        },
        {
            "name": "testo 549i",
            "serial": "13379501"
        }
    ],
    "properties": [
        {
            "description": "refrigerant",
            "name": "refrigerant",
            "values": [
                {
                    "description": "R23",
                    "name": "refrigerantValue",
                    "value": "R23"
                }
            ]
        },
        {
            "description": "pressureType",
            "name": "pressureType",
            "values": [
                {
                    "description": "P<sub>rel</sub>",
                    "name": "pressureTypeValue",
                    "value": "P<sub>rel</sub>"
                }
            ]
        },
        {
            "description": "returnAirWetBulb",
            "name": "returnAirWetBulb",
            "values": [
                {
                    "description": "10 wb °C",
                    "name": "returnAirWetBulbValue",
                    "value": 10
                }
            ]
        },
        {
            "description": "outdoorDryBulb",
            "name": "outdoorDryBulb",
            "values": [
                {
                    "description": "12.8 °C",
                    "name": "outdoorDryBulbValue",
                    "value": 12.800000190734863
                }
            ]
        }
    ],
    "schemaVersion": "1.0.2",
    "timeStamp": "2017-07-26T10:51:16",
    "type": {
        "name": "Zielüberhitzung"
    }
}
